version: '3.8'
services:
  front:
    container_name: frontend
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  database:
    container_name: database
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  jenkins-ci:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - ./jenkins_home:/app/jenkins_home
